### ISSUE TITLE
Hide tooltip options for code blocks

### ISSUE THREAD

**Issue by SwapnilChand** [Cloud-Code-AI/AkiraDocs#172]
![Screenshot 2024-12-04 091417](https://github.com/user-attachments/assets/9de0885f-c1e6-442d-b091-4fc22367bc71)

**Comment by SwapnilChand** [comment]
Code blocks cant have styles, or alignments.

**Comment by sauravpanda** [comment]
good point, code blocks should instead have language type? @shreyashkgupta will that be complicated?

**Comment by SwapnilChand** [comment]
No maybe that will be unnecessary, but perhaps IDE like color coding will be great.

**Comment by shreyashkgupta** [comment]
The code blocks already have a language type - the result thougj is only visible when you click outside the block. The input in toolbar that says JavaScript can be changed to any other language. Rendering while editing like IDE wes breaking the view.

I'll hide the other text formatting options. Shouldn't be complicated.

**Comment by sauravpanda** [comment]
Awesome!
