### ISSUE TITLE
change the way we handle meta.json

### ISSUE THREAD

**Issue by sauravpanda** [Cloud-Code-AI/AkiraDocs#189]
meta.json is used for our naviagtion system, its currently generated on compilation but because of that we lose the capability to order the pages, we should change how we structure the meta.json so that its easier for users to navigate and order the files!

**Comment by sauravpanda** [comment]
@shreyashkgupta one idea I have been considering is adding a config field where users can say if they want the meta.json autogenerated.

They can manually edit the meta.json (using UI or directly the JSON) and we can reflect changes in all other locales.

We can also add a red-colored warning during compile to point to any file that isn't part of meta data.

**Comment by shreyashkgupta** [comment]
> @shreyashkgupta one idea I have been considering is adding a config field where users can say if they want the meta.json autogenerated.
> 
> They can manually edit the meta.json (using UI or directly the JSON) and we can reflect changes in all other locales.
> 
> We can also add a red-colored warning during compile to point to any file that isn't part of meta data.

Sounds like a good idea. I'll look into it. We should definitely allow editing the _meta.json files.
