### ISSUE TITLE
Show Add File/Folder/Delete Options in a Context Menu in Project Explorer

### ISSUE THREAD

**Issue by SwapnilChand** [Cloud-Code-AI/AkiraDocs#200]
![Screenshot 2024-12-10 144202](https://github.com/user-attachments/assets/fe2385da-d23b-4b55-b818-a096c7f42684)
## Feature Request

This issue proposes a modification to the Project Explorer interface. Currently, the options to add files, folders, and delete items , as well as the parent folder lines and the scroll bar are always visible, which can contribute to a cluttered appearance. It is suggested that these options be displayed only when the user hovers over the Project Explorer area.

### Benefits:
- **Enhanced Aesthetics:** A cleaner interface without the constant visibility of options.
- **User Focus:** Reduces distractions, allowing users to concentrate on their files and folders.
- **Intuitive Interaction:** Contextual options appearing on hover align with common user expectations, improving usability.

**Comment by sauravpanda** [comment]
This sounds like good idea, we should try to work on it. Can you help?

**Comment by SwapnilChand** [comment]
Definitely! Already working on this, also taking a look at other editor related issues and fixes I have created in the past.
