### ISSUE TITLE
Custom Component Block

### ISSUE THREAD

**Issue by sauravpanda** [Cloud-Code-AI/AkiraDocs#201]
I was thinking we should have a custom component block that users can edit (maybe as HTML).

One of my ideas was to add a button to the articles pointing to our GitHub Repo? 

What other components or elements do you think will help? @shreyashkgupta

**Comment by shreyashkgupta** [comment]
I'm wondering if we should make the button component ourselves so that we can control the json structure properly.
Button component in general is a good idea.

**Comment by shreyashkgupta** [comment]
Using this branch to add a spacer and button block
